services:
  - type: web
    name: expensetracker-pwa
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python database.py
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
